-- ============================================================================
-- CREACIÓN DE NUEVA ESTRUCTURA NORMALIZADA
-- Schema: kpidata
-- ============================================================================

-- Crear schema si no existe
CREATE SCHEMA IF NOT EXISTS kpidata;

-- ============================================================================
-- TABLA 1: conversations (nivel de chat/conversación)
-- ============================================================================
CREATE TABLE IF NOT EXISTS kpidata.conversations (
  chat_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc-4:00'::text),
  title TEXT NOT NULL DEFAULT 'Desconocido'::text,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  user_assign UUID NULL,
  role_assign TEXT NULL,
  
  CONSTRAINT conversations_pkey PRIMARY KEY (chat_id),
  CONSTRAINT conversations_role_assign_fkey FOREIGN KEY (role_assign) 
    REFERENCES roles (role_key),
  CONSTRAINT conversations_user_assign_fkey FOREIGN KEY (user_assign) 
    REFERENCES profiles (user_id)
) TABLESPACE pg_default;

-- Índices para conversations
CREATE INDEX IF NOT EXISTS idx_conversations_created_at 
  ON kpidata.conversations(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_conversations_user_assign 
  ON kpidata.conversations(user_assign);

CREATE INDEX IF NOT EXISTS idx_conversations_updated_at 
  ON kpidata.conversations(updated_at DESC);

-- Comentarios
COMMENT ON TABLE kpidata.conversations IS 'Conversaciones/chats únicos del sistema';
COMMENT ON COLUMN kpidata.conversations.metadata IS 'Datos adicionales: canal, estado, tags, etc';

-- ============================================================================
-- TABLA 2: messages (nivel de mensaje individual)
-- ============================================================================
CREATE TABLE IF NOT EXISTS kpidata.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc-4:00'::text),
  role TEXT NOT NULL, -- 'user', 'assistant', 'system'
  content TEXT NULL,
  message_type TEXT NOT NULL, -- 'text', 'image', 'audio', 'video', 'document'
  media_url TEXT NULL,
  tokens BIGINT NULL,
  chat_id TEXT NOT NULL,
  media_id UUID NULL,
  media_directory TEXT NULL,
  user_id TEXT NOT NULL,
  
  -- Campos adicionales para tokens separados (opcional)
  input_tokens BIGINT NULL,
  output_tokens BIGINT NULL,
  
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) 
    REFERENCES kpidata.conversations (chat_id) ON DELETE CASCADE,
  CONSTRAINT messages_media_id_fkey FOREIGN KEY (media_id) 
    REFERENCES kpidata.multimedia_incoming (media_id)
) TABLESPACE pg_default;

-- Índices para messages
CREATE INDEX IF NOT EXISTS idx_messages_chat_id 
  ON kpidata.messages(chat_id);

CREATE INDEX IF NOT EXISTS idx_messages_created_at 
  ON kpidata.messages(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_messages_user_id 
  ON kpidata.messages(user_id);

CREATE INDEX IF NOT EXISTS idx_messages_role 
  ON kpidata.messages(role);

CREATE INDEX IF NOT EXISTS idx_messages_message_type 
  ON kpidata.messages(message_type);

-- Comentarios
COMMENT ON TABLE kpidata.messages IS 'Mensajes individuales dentro de conversaciones';
COMMENT ON COLUMN kpidata.messages.role IS 'user: mensaje del usuario, assistant: respuesta de IA, system: mensaje del sistema';
COMMENT ON COLUMN kpidata.messages.message_type IS 'Tipo de mensaje: text, image, audio, video, document';

-- ============================================================================
-- TRIGGER PARA ACTUALIZAR updated_at EN CONVERSATIONS
-- ============================================================================
CREATE OR REPLACE FUNCTION kpidata.update_conversation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE kpidata.conversations
  SET updated_at = NEW.created_at
  WHERE chat_id = NEW.chat_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_conversation_timestamp
AFTER INSERT ON kpidata.messages
FOR EACH ROW
EXECUTE FUNCTION kpidata.update_conversation_timestamp();

-- ============================================================================
-- VISTAS ÚTILES
-- ============================================================================

-- Vista: Última actividad por conversación
CREATE OR REPLACE VIEW kpidata.v_conversations_summary AS
SELECT 
  c.chat_id,
  c.title,
  c.created_at,
  c.updated_at,
  c.user_assign,
  c.role_assign,
  COUNT(m.id) as total_messages,
  SUM(COALESCE(m.tokens, 0)) as total_tokens,
  MAX(m.created_at) as last_message_at
FROM kpidata.conversations c
LEFT JOIN kpidata.messages m ON c.chat_id = m.chat_id
GROUP BY c.chat_id, c.title, c.created_at, c.updated_at, c.user_assign, c.role_assign;

COMMENT ON VIEW kpidata.v_conversations_summary IS 'Resumen de conversaciones con contadores agregados';

-- ============================================================================
-- GRANTS (Permisos para roles de Supabase)
-- ============================================================================

-- Permisos para usuarios no autenticados (anon)
GRANT USAGE ON SCHEMA kpidata TO anon;
GRANT SELECT ON kpidata.conversations TO anon;
GRANT SELECT ON kpidata.messages TO anon;
GRANT SELECT ON kpidata.v_conversations_summary TO anon;

-- Permisos para usuarios autenticados
GRANT USAGE ON SCHEMA kpidata TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON kpidata.conversations TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON kpidata.messages TO authenticated;
GRANT SELECT ON kpidata.v_conversations_summary TO authenticated;

-- Permisos en secuencia para INSERT
GRANT USAGE, SELECT ON SEQUENCE kpidata.messages_id_seq TO authenticated;

-- ============================================================================
COMMENT ON SCHEMA kpidata IS 'Schema para datos de KPI y conversaciones normalizadas';
