-- ════════════════════════════════════════════════════════════════════════════
-- PRUEBA DE MIGRACIÓN CON ROLLBACK
-- ════════════════════════════════════════════════════════════════════════════
-- Este script ejecuta la migración completa en una transacción y hace ROLLBACK
-- para verificar que todo funciona correctamente SIN modificar la base de datos
--
-- IMPORTANTE: Este script NO modifica permanentemente la base de datos
-- ════════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  RAISE NOTICE '';
  RAISE NOTICE '════════════════════════════════════════════════════════════════';
  RAISE NOTICE '  PRUEBA DE MIGRACIÓN (CON ROLLBACK)';
  RAISE NOTICE '  Los cambios NO serán permanentes';
  RAISE NOTICE '  Inicio: %', now();
  RAISE NOTICE '════════════════════════════════════════════════════════════════';
  RAISE NOTICE '';
END $$;

-- ============================================================================
-- INICIAR TRANSACCIÓN
-- ============================================================================
BEGIN;

-- ============================================================================
-- PASO 1: VERIFICAR DATOS ORIGINALES
-- ============================================================================
DO $$
DECLARE
  v_orig_count INTEGER;
  v_unique_chats INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_orig_count FROM kpi_data_sofia.conversations;
  SELECT COUNT(DISTINCT REPLACE(chat_id, '@s.whatsapp.net', '')) 
    INTO v_unique_chats 
    FROM kpi_data_sofia.conversations 
    WHERE chat_id IS NOT NULL;
  
  RAISE NOTICE '▶ DATOS ORIGINALES:';
  RAISE NOTICE '  • Total registros: %', v_orig_count;
  RAISE NOTICE '  • Conversaciones únicas (normalizadas): %', v_unique_chats;
  RAISE NOTICE '';
END $$;

-- ============================================================================
-- PASO 2: CREAR ESTRUCTURA (si no existe)
-- ============================================================================
RAISE NOTICE '▶ CREANDO ESTRUCTURA...';

-- Crear schema
CREATE SCHEMA IF NOT EXISTS kpidata;

-- Crear tabla conversations
CREATE TABLE IF NOT EXISTS kpidata.conversations (
  chat_id TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc-4:00'::text),
  title TEXT NOT NULL DEFAULT 'Desconocido'::text,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMP WITH TIME ZONE NULL,
  user_assign UUID NULL,
  role_assign TEXT NULL,
  
  CONSTRAINT conversations_pkey PRIMARY KEY (chat_id)
) TABLESPACE pg_default;

-- Crear tabla messages
CREATE TABLE IF NOT EXISTS kpidata.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (now() AT TIME ZONE 'utc-4:00'::text),
  role TEXT NOT NULL,
  content TEXT NULL,
  message_type TEXT NOT NULL,
  media_url TEXT NULL,
  tokens BIGINT NULL,
  chat_id TEXT NOT NULL,
  media_id UUID NULL,
  media_directory TEXT NULL,
  user_id TEXT NOT NULL,
  input_tokens BIGINT NULL,
  output_tokens BIGINT NULL,
  
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) 
    REFERENCES kpidata.conversations (chat_id) ON DELETE CASCADE
) TABLESPACE pg_default;

RAISE NOTICE '  ✓ Estructura creada';
RAISE NOTICE '';

-- ============================================================================
-- PASO 3: MIGRAR CONVERSACIONES
-- ============================================================================
RAISE NOTICE '▶ MIGRANDO CONVERSACIONES...';

INSERT INTO kpidata.conversations (
  chat_id,
  created_at,
  title,
  metadata,
  updated_at,
  user_assign,
  role_assign
)
WITH normalized_chats AS (
  SELECT 
    DISTINCT ON (REPLACE(COALESCE(chat_id, 'migrated_' || id::text), '@s.whatsapp.net', ''))
    REPLACE(COALESCE(chat_id, 'migrated_' || id::text), '@s.whatsapp.net', '') as normalized_chat_id,
    created_at,
    message_content,
    user_channel,
    system_channel,
    file,
    user_id,
    chat_id as original_chat_id
  FROM kpi_data_sofia.conversations
  ORDER BY REPLACE(COALESCE(chat_id, 'migrated_' || id::text), '@s.whatsapp.net', ''), created_at ASC
),
chat_stats AS (
  SELECT 
    REPLACE(COALESCE(chat_id, 'migrated_' || id::text), '@s.whatsapp.net', '') as normalized_chat_id,
    MIN(created_at) as first_msg,
    MAX(created_at) as last_msg,
    COUNT(*) as msg_count,
    BOOL_OR(COALESCE(file, false)) as has_files
  FROM kpi_data_sofia.conversations
  GROUP BY REPLACE(COALESCE(chat_id, 'migrated_' || id::text), '@s.whatsapp.net', '')
)
SELECT 
  nc.normalized_chat_id as chat_id,
  nc.created_at,
  COALESCE(LEFT(nc.message_content, 50), 'Conversación sin título') as title,
  jsonb_build_object(
    'original_schema', 'kpi_data_sofia',
    'user_channel', nc.user_channel,
    'system_channel', nc.system_channel,
    'has_files', cs.has_files,
    'migrated_at', now(),
    'total_messages_at_migration', cs.msg_count,
    'original_chat_id_format', nc.original_chat_id
  ) as metadata,
  cs.last_msg as updated_at,
  CASE 
    WHEN nc.user_id ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
    THEN nc.user_id::uuid
    ELSE NULL
  END as user_assign,
  NULL as role_assign
FROM normalized_chats nc
JOIN chat_stats cs ON nc.normalized_chat_id = cs.normalized_chat_id;

DO $$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM kpidata.conversations;
  RAISE NOTICE '  ✓ Conversaciones migradas: %', v_count;
  RAISE NOTICE '';
END $$;

-- ============================================================================
-- PASO 4: MIGRAR MENSAJES
-- ============================================================================
RAISE NOTICE '▶ MIGRANDO MENSAJES...';

-- Mensajes del usuario/sistema
INSERT INTO kpidata.messages (
  created_at, role, content, message_type, media_url, tokens,
  chat_id, media_id, media_directory, user_id, input_tokens, output_tokens
)
SELECT 
  created_at,
  CASE 
    WHEN message_content IS NULL THEN 'system'
    ELSE 'user'
  END as role,
  COALESCE(message_content, '[mensaje del sistema]') as content,
  CASE WHEN file = true THEN 'document' ELSE 'text' END as message_type,
  NULL as media_url,
  COALESCE(input_token, 0) as tokens,
  REPLACE(COALESCE(chat_id, 'migrated_' || id::text), '@s.whatsapp.net', '') as chat_id,
  NULL, NULL,
  COALESCE(user_id, 'unknown') as user_id,
  input_token, NULL
FROM kpi_data_sofia.conversations;

DO $$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM kpidata.messages WHERE role IN ('user', 'system');
  RAISE NOTICE '  ✓ Mensajes usuario/sistema: %', v_count;
END $$;

-- Respuestas del asistente
INSERT INTO kpidata.messages (
  created_at, role, content, message_type, media_url, tokens,
  chat_id, media_id, media_directory, user_id, input_tokens, output_tokens
)
SELECT 
  created_at + INTERVAL '1 second',
  'assistant' as role,
  response as content,
  'text' as message_type,
  NULL, COALESCE(output_token, 0),
  REPLACE(COALESCE(chat_id, 'migrated_' || id::text), '@s.whatsapp.net', ''),
  NULL, NULL,
  'sofia_system',
  NULL, output_token
FROM kpi_data_sofia.conversations
WHERE response IS NOT NULL;

DO $$
DECLARE
  v_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM kpidata.messages WHERE role = 'assistant';
  RAISE NOTICE '  ✓ Mensajes asistente: %', v_count;
  RAISE NOTICE '';
END $$;

-- ============================================================================
-- PASO 5: VALIDACIONES
-- ============================================================================
RAISE NOTICE '▶ EJECUTANDO VALIDACIONES...';
RAISE NOTICE '';

-- Validación 1: Conversaciones sin mensajes
DO $$
DECLARE
  v_orphan_convs INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_orphan_convs
  FROM kpidata.conversations c
  LEFT JOIN kpidata.messages m ON c.chat_id = m.chat_id
  WHERE m.id IS NULL;
  
  IF v_orphan_convs > 0 THEN
    RAISE WARNING '  ⚠ Conversaciones sin mensajes: %', v_orphan_convs;
  ELSE
    RAISE NOTICE '  ✓ Todas las conversaciones tienen mensajes';
  END IF;
END $$;

-- Validación 2: Mensajes huérfanos
DO $$
DECLARE
  v_orphan_msgs INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_orphan_msgs
  FROM kpidata.messages m
  LEFT JOIN kpidata.conversations c ON m.chat_id = c.chat_id
  WHERE c.chat_id IS NULL;
  
  IF v_orphan_msgs > 0 THEN
    RAISE ERROR '  ✗ ERROR: Mensajes sin conversación: %', v_orphan_msgs;
  ELSE
    RAISE NOTICE '  ✓ Todos los mensajes tienen conversación válida';
  END IF;
END $$;

-- Validación 3: Distribución de roles
DO $$
DECLARE
  v_user INTEGER;
  v_assistant INTEGER;
  v_system INTEGER;
BEGIN
  SELECT 
    COUNT(*) FILTER (WHERE role = 'user'),
    COUNT(*) FILTER (WHERE role = 'assistant'),
    COUNT(*) FILTER (WHERE role = 'system')
  INTO v_user, v_assistant, v_system
  FROM kpidata.messages;
  
  RAISE NOTICE '  ✓ Distribución de roles:';
  RAISE NOTICE '    - user: %', v_user;
  RAISE NOTICE '    - assistant: %', v_assistant;
  RAISE NOTICE '    - system: %', v_system;
END $$;

-- Validación 4: Duplicados detectados y unificados
DO $$
DECLARE
  v_original_distinct INTEGER;
  v_normalized_distinct INTEGER;
  v_unified INTEGER;
BEGIN
  SELECT COUNT(DISTINCT chat_id) 
    INTO v_original_distinct 
    FROM kpi_data_sofia.conversations 
    WHERE chat_id IS NOT NULL;
    
  SELECT COUNT(*) 
    INTO v_normalized_distinct 
    FROM kpidata.conversations;
  
  v_unified := v_original_distinct - v_normalized_distinct;
  
  RAISE NOTICE '';
  RAISE NOTICE '  ✓ Normalización de chat_id:';
  RAISE NOTICE '    - Conversaciones originales distintas: %', v_original_distinct;
  RAISE NOTICE '    - Conversaciones después de normalizar: %', v_normalized_distinct;
  RAISE NOTICE '    - Duplicados unificados: %', v_unified;
END $$;

RAISE NOTICE '';

-- ============================================================================
-- PASO 6: EJEMPLO DE CONVERSACIÓN MIGRADA
-- ============================================================================
RAISE NOTICE '▶ EJEMPLO DE CONVERSACIÓN MIGRADA:';
RAISE NOTICE '';

DO $$
DECLARE
  v_chat_id TEXT;
  v_title TEXT;
  v_msg_count INTEGER;
  v_channel TEXT;
BEGIN
  SELECT 
    c.chat_id,
    c.title,
    COUNT(m.id),
    c.metadata->>'user_channel'
  INTO v_chat_id, v_title, v_msg_count, v_channel
  FROM kpidata.conversations c
  LEFT JOIN kpidata.messages m ON c.chat_id = m.chat_id
  GROUP BY c.chat_id, c.title, c.metadata
  ORDER BY COUNT(m.id) DESC
  LIMIT 1;
  
  RAISE NOTICE '  Chat ID: %', v_chat_id;
  RAISE NOTICE '  Título: %', v_title;
  RAISE NOTICE '  Total mensajes: %', v_msg_count;
  RAISE NOTICE '  Canal: %', v_channel;
END $$;

RAISE NOTICE '';

-- ============================================================================
-- RESUMEN FINAL
-- ============================================================================
DO $$
DECLARE
  v_orig INTEGER;
  v_convs INTEGER;
  v_msgs INTEGER;
BEGIN
  SELECT COUNT(*) INTO v_orig FROM kpi_data_sofia.conversations;
  SELECT COUNT(*) INTO v_convs FROM kpidata.conversations;
  SELECT COUNT(*) INTO v_msgs FROM kpidata.messages;
  
  RAISE NOTICE '════════════════════════════════════════════════════════════════';
  RAISE NOTICE '  RESUMEN DE PRUEBA DE MIGRACIÓN';
  RAISE NOTICE '════════════════════════════════════════════════════════════════';
  RAISE NOTICE '';
  RAISE NOTICE '📊 RESULTADOS:';
  RAISE NOTICE '   • Registros originales: %', v_orig;
  RAISE NOTICE '   • Conversaciones creadas: %', v_convs;
  RAISE NOTICE '   • Mensajes creados: %', v_msgs;
  RAISE NOTICE '   • Ratio mensajes/conversación: %', ROUND(v_msgs::numeric / v_convs, 2);
  RAISE NOTICE '';
  RAISE NOTICE '✅ PRUEBA EXITOSA - Todo funcionó correctamente';
  RAISE NOTICE '';
  RAISE NOTICE '⚠️  AHORA SE EJECUTARÁ ROLLBACK';
  RAISE NOTICE '   Los cambios NO serán permanentes';
  RAISE NOTICE '';
  RAISE NOTICE '════════════════════════════════════════════════════════════════';
  RAISE NOTICE '';
END $$;

-- ============================================================================
-- ROLLBACK - DESHACER TODOS LOS CAMBIOS
-- ============================================================================
ROLLBACK;

DO $$
BEGIN
  RAISE NOTICE '🔙 ROLLBACK EJECUTADO - Base de datos sin cambios';
  RAISE NOTICE '';
  RAISE NOTICE '📝 PRÓXIMOS PASOS:';
  RAISE NOTICE '   1. Revisar los resultados arriba';
  RAISE NOTICE '   2. Si todo se ve bien, ejecutar: 00_migration_master.sql';
  RAISE NOTICE '   3. Ese script hará los cambios permanentes (sin ROLLBACK)';
  RAISE NOTICE '';
END $$;
